### ISSUE TITLE
Model element "Deployment Model" cannot be added with Camel Designer v1 0 05 

### ISSUE THREAD

**Issue by alebagnato** [Modelio-R-D/CamelDesigner#100]
Hi All,
Just to notify that in the last release of Camel Designer v1 0 05 we cannot add the model element "Deployment Model", all the other models are nicely created (as in the enclosed screen)
Many thanks in advance for your help
Alessandra
![image](https://user-images.githubusercontent.com/9965053/152496908-dc6ee70c-7436-482a-a70c-9c9b6f76a519.png)
![CAMELCamel Designer v1 0 05-nodeploymentelementcanbeadded](https://user-images.githubusercontent.com/9965053/152497425-86746cc2-fecb-45a8-95fc-2ee3abe5df7d.jpg)

**Comment by Amina-Moussaoui** [comment]
Fixed in  V1.0.06 .
