### ISSUE TITLE
Service Level Objective & Service_Level_Objective of  "Requirement Model" cannot be added with Camel Designer v1 0 05

### ISSUE THREAD

**Issue by alebagnato** [Modelio-R-D/CamelDesigner#101]
Hi All,
Just to notify that in the last release of Camel Designer v1 0 05 we cannot add the Service Level Objective & Service_Level_Objective, all the other elements of the Modelio palette are nicely created (as in the enclosed screen Location Requirements etc are correctly appearing)
Many thanks in advance for your help
Alessandra

![image](https://user-images.githubusercontent.com/9965053/152499110-093e2316-e1ab-4f70-b0a7-ca9a4462be48.png)

**Comment by etiennebrosse** [comment]
Fixed in 1.0.06 (rev 481)
