### ISSUE TITLE
Adding "Measurement" in "Execution Model" generate an "Alert Model Shield" with Camel Designer v1 0 05

### ISSUE THREAD

**Issue by alebagnato** [Modelio-R-D/CamelDesigner#103]
Hi All,
Just to notify that in the last release of Camel Designer v1 0 05 Adding "Measurement" in "Execution Model" generate an "Alert Model Shield". I am adding related screenshot in this issue
Many thanks in advance for your help
Alessandra
![image](https://user-images.githubusercontent.com/9965053/152500644-6ae4a094-3f8a-40a5-b036-0f958574baf0.png)
![AlerteModelShield](https://user-images.githubusercontent.com/9965053/152500813-8fc7c6ca-5312-4fef-9f02-85030ce7e734.jpg)

**Comment by Amina-Moussaoui** [comment]
Measurement shouldn't be in the execution model tools.
Issue fixed in v1.0.06

**Comment by alebagnato** [comment]
Many thanks!
