### ISSUE TITLE
MMSConceptInstance, MMS Property and MMS Property instance of "Metadata Model"/""Metadat Diagram" cannot be added with Camel Designer v1 0 05

### ISSUE THREAD

**Issue by alebagnato** [Modelio-R-D/CamelDesigner#104]
Hi All,
Just to notify that in the last release of Camel Designer v1 0 05 we cannot add
MMSConceptInstance, MMS Property and MMS Property instance of "Metadata Model"/""Metadat Diagram" cannot be added with Camel Designer v1 0 05.
Only MMS Concept can be added in the diagram as in the enclosed image
![image](https://user-images.githubusercontent.com/9965053/152501561-59557c3d-f168-4609-888d-7454a845fb2f.png)
Many thanks for your help
Alessandra

**Comment by Amina-Moussaoui** [comment]
-MMSConceptInstance can be created inside the class MmsConcept
-MMSProperty can be created inside the class MmsConcept
-MMSPropertyInstance can be created inside the instance MmsConceptInstance
![Capture](https://user-images.githubusercontent.com/87063598/152562150-58887cfb-43cc-4922-b7ac-1267d73a2436.PNG)
