### ISSUE TITLE
Adding "Scaling Action" in "Scalability Model" generate an "Alert Model Shield" with Camel Designer v1 0 05

### ISSUE THREAD

**Issue by alebagnato** [Modelio-R-D/CamelDesigner#105]
Hi All,
Just to notify that in the last release of Camel Designer v1 0 05
Adding "Scaling Action" in "Scalability Model" generate an "Alert Model Shield" with Camel Designer v1 0 05

Image is enclosed 
![image](https://user-images.githubusercontent.com/9965053/152502729-6d2425e5-b44e-4da6-8e0b-2528fd8a2607.png)
Many thanks for your help!
Best Regards,
Alessandra

**Comment by Amina-Moussaoui** [comment]
Issue fixed in V1.0.06
