### ISSUE TITLE
Adding "Unit" in "Unit Model" generate an "Alert Model Shield" with Camel Designer v1 0 05

### ISSUE THREAD

**Issue by alebagnato** [Modelio-R-D/CamelDesigner#106]
Hi All,
Just to notify that in the last release of Camel Designer v1 0 05 Adding "Unit" in "Unit Model" generate an "Alert Model Shield" with Camel Designer v1 0 05, please find the image enclosed 
Many thanks for your help,
Alessandra

![image](https://user-images.githubusercontent.com/9965053/152502991-cfd86c77-6417-4e3f-bc7f-e9c54fa8309f.png)

**Comment by Amina-Moussaoui** [comment]
Issue fixed in V 1.0.06
