### ISSUE TITLE
Export of Security Model doesnt work

### ISSUE THREAD

**Issue by alebagnato** [Modelio-R-D/CamelDesigner#109]
<img width="960" alt="Capture d'écran 2022-04-20 17 27 08" src="https://user-images.githubusercontent.com/9965053/164266901-354af155-1352-4058-9058-16dc59114b8a.png">
Dear all,
Please find herewith a test of the export of the security model, the export doesnt include all the elements
Best Regards and thanks,
Alessandra

**Comment by etiennebrosse** [comment]
The Modelio model would be helpful.

**Comment by alebagnato** [comment]
Sent!

**Comment by etiennebrosse** [comment]
Fixed in 1.0.09
