### ISSUE TITLE
Export of Security Control doesnt work

### ISSUE THREAD

**Issue by alebagnato** [Modelio-R-D/CamelDesigner#110]
Dear All,
Please find herewith a project containing three security controls with the incomplete export file that I get as export result: ![Security Diagram](https://user-images.githubusercontent.com/9965053/164411947-d92c82ac-346c-4631-971a-487944bc9720.png)
 
The complete modelio project is at https://www.dropbox.com/s/4emjzvt1vrwunde/CAMELSecurityMODEL.zip?dl=0

Best Regards and many thanks in advance for your help,
Alessandra
ps
<?xml version="1.0" encoding="ASCII"?>
<core:CamelModel xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:core="http://www.camel-dsl.org/camel/core" name="CamelModel">
  <application name="CamelModel"/>
</core:CamelModel>

**Comment by etiennebrosse** [comment]
Fixed in 1.0.09
