### ISSUE TITLE
Location Model export with Camel Designer v1.0.09

### ISSUE THREAD

**Issue by alebagnato** [Modelio-R-D/CamelDesigner#111]
Hi All,
Regions DE & UK of parent region EU are not exported in the following project
![Location diagram DE UK](https://user-images.githubusercontent.com/9965053/164747618-f515d785-04e4-44f5-8058-e2599e31f72c.png)
I also do not see Organization , Execution and Scalability Model headers in the export
Zipped archive of the project at https://www.dropbox.com/s/vyi2xkk3kob2eqc/CAMELModelExample3May.zip?dl=0
Best Regards and thanks,
Alessandra
ps
<?xml version="1.0" encoding="ASCII"?>
<core:CamelModel xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:core="http://www.camel-dsl.org/camel/core" xmlns:data="http://www.camel-dsl.org/camel/data" xmlns:deployment="http://www.camel-dsl.org/camel/deployment" xmlns:metric="http://www.camel-dsl.org/camel/metric" name="CamelModel">
  <application name="CamelModel"/>
  <deploymentModels xsi:type="deployment:DeploymentTypeModel" name="Deployment Type Model"/>
  <deploymentModels xsi:type="deployment:DeploymentInstanceModel" name="Deployment Instance Model"/>
  <locationModels name="Location Model">
    <cloudLocations name="Cloud Location"/>
    <regions name="EU" description="Europa"/>
  </locationModels>
  <metricModels xsi:type="metric:MetricTypeModel" name="Metric Type Model"/>
  <metricModels xsi:type="metric:MetricInstanceModel" name="Metric Instance Model"/>
  <requirementModels name="Requirement Type Model"/>
  <securityModels name="Security Model"/>
  <dataModels xsi:type="data:DataTypeModel" name="Data Type Model"/>
  <dataModels xsi:type="data:DataInstanceModel" name="Data Instance Model"/>
  <metadataModels name="Metadata Model"/>
</core:CamelModel>

**Comment by etiennebrosse** [comment]
According to Camel language, Region can not contain other région. That's why DE and UK are not exported.
