### ISSUE TITLE
Scalability Model is in the Scalability palette with Camel Designer v1.0.09 

### ISSUE THREAD

**Issue by alebagnato** [Modelio-R-D/CamelDesigner#112]
Dear All,
The scalability Model also appear in the scalability model palette with with Camel Designer v1.0.09 
Clicking on it produce a new Scalability Model diagram
<img width="960" alt="Capture d'écran 2022-04-22 17 48 12" src="https://user-images.githubusercontent.com/9965053/164749736-fc9854af-3aa2-446a-be30-46cb90b4858f.png">
 
Best Regards and thanks,
Alessandra

**Comment by etiennebrosse** [comment]
Solved in CAmel Designer 1.0.10
