### ISSUE TITLE
Execution, Organization and Scalability Models export doesnt work with Camel Designer v1.0.09

### ISSUE THREAD

**Issue by alebagnato** [Modelio-R-D/CamelDesigner#113]
Dear All,

The export for the Execution, Organization and Scalability Models doesn work with the  new release of Camel Designer v1.0.09

<img width="960" alt="Capture d'écran 2022-04-22 17 57 59" src="https://user-images.githubusercontent.com/9965053/164751377-1a569324-2afa-49f2-830a-9d0dc1d0e667.png">

Please see the modelio project at https://www.dropbox.com/s/sxga96wi9aq6jc1/TestingExport%201.0.9.zip?dl=0
and the received export file in the ps of this message
Best Regards and thanks
Alessandra 
ps

<?xml version="1.0" encoding="ASCII"?>
<core:CamelModel xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:core="http://www.camel-dsl.org/camel/core" name="CamelModel">
  <application name="CamelModel"/>
</core:CamelModel>

**Comment by etiennebrosse** [comment]
Solved in Camel Designer 1.0.10
