### ISSUE TITLE
Exporting attributes in Location Model with Camel Designer v1.0.10

### ISSUE THREAD

**Issue by alebagnato** [Modelio-R-D/CamelDesigner#114]
Dear All,
It seems that the attributes in the  Location Model with Camel Designer v1.0.10 are not exported in the xmi file.
Please fid herewith the zipped archive of my Modelio Model and the screen of the model https://www.dropbox.com/s/qnpv5mse3op2bk7/TestCAMEL10.zip?dl=
![Location diagram-attributesnotexported](https://user-images.githubusercontent.com/9965053/172629637-16ebe963-8083-4870-a172-a77bb15facbb.png)
0
LocationModels only contains the features declared as in the export in the ps in here
Best Regards and thanks,
Alessandra
ps 
 <locationModels name="Location Model">
    <cloudLocations name="Cloud Location">
      <subFeatures name="Feature"/>
    </cloudLocations>
    <regions name="Region">
      <subFeatures name="Feature"/>
    </regions>
  </locationModels>

**Comment by etiennebrosse** [comment]
Fixed in 1.0.11

**Comment by alebagnato** [comment]
Thanks!
