### ISSUE TITLE
PaaS requirement are not exported

### ISSUE THREAD

**Issue by etiennebrosse** [Modelio-R-D/CamelDesigner#116]
Paas requirements are not exported.

Steps to reproduce:
1. Create a Camel Model
2. Create a Requirement Model
3. Create a PaaS requirement
=>PaaS requirement are not in the generated XMI file

**Comment by Amina-Moussaoui** [comment]
The API has been updated to export the PaaSRequirement. 
The PaaSRequirement is exported as long as you add a 4th step:

1.Create a Camel Model
2.Create a Requirement Model
3.Create a PaaS requirement
4.Attach it to another requirement (ImageReq /HorizontalReq/ ResourceReq) as a subfeature
