### ISSUE TITLE
"Alerte Model Shield" while adding  Unit element to a the Unit Model Diagram in Camel Designer Beta version 0.1.05

### ISSUE THREAD

**Issue by alebagnato** [Modelio-R-D/CamelDesigner#2]
Hi there,

I am using Camel Designer Beta version 0.1.05 and im getting "Alerte Model Shield"  when I try to add a Unit element to a the Unit  Model Diagram, Please see the screenshot enclosed.
Many thanks in advacne for your help! Alessandra
 
E297: Le stéréotype abstrait ''Unit'{56c9f56b-274d-4816-80c8-72536d1d7295} Infrastructure.Stereotype' est appliqué à l'élément ''Unit'{4c81ec53-4665-4864-9532-171e99f3d345} Standard.DataType'.
![cameldesignerTC2UnitModelDiagramUnitElement](https://user-images.githubusercontent.com/9965053/99697374-fab83c00-2a8f-11eb-812a-397ddd5fb4d2.jpg)

Un stéréotype abstrait peut ne pas être applicable à n''importe quel élément.

**Comment by etiennebrosse** [comment]
Solved in 0.0.16
