### ISSUE TITLE
Deployment Diagram palette tools doesn't allow creation of elements ProvidedHost, RequiredHost, ProvidedCommunication, RequiredCommunication

### ISSUE THREAD

**Issue by kaischaabouni** [Modelio-R-D/CamelDesigner#24]
Deployment Diagram palette tools doesn't allow creation of elements 
- ProvidedHost
- RequiredHost
- ProvidedCommunication
- RequiredCommunication

**Comment by etiennebrosse** [comment]
Fixed in 1.0.01
