### ISSUE TITLE
Impossible to add a ResourceRequirement to the Requirement Model Diagram

### ISSUE THREAD

**Issue by alebagnato** [Modelio-R-D/CamelDesigner#3]
Hi there,
I am using Camel Designer Beta version 0.1.05 and I seem not to be able to add a ResourceRequirement to the Requirement Model Diagram
![cameldesignerTC3-AddingResi](https://user-images.githubusercontent.com/9965053/99699441-3bb15000-2a92-11eb-9dde-a6207b53dd7a.jpg)
, Please see the screenshot enclosed.
cameldesignerTC3-AddingResourceRequirementtoRequirementModelDiagram.jpg

**Comment by etiennebrosse** [comment]
Fixed

**Comment by alebagnato** [comment]
Thanks :)
