### ISSUE TITLE
Missing methods in api MetricTemplate  for setting dependency to measurable attribue, unit, valueType

### ISSUE THREAD

**Issue by kaischaabouni** [Modelio-R-D/CamelDesigner#6]
Lacking methods in api MetricTemplate for for setting dependency to measurable  attribue, unit, valueType

**Comment by etiennebrosse** [comment]
Added

**Comment by kaischaabouni** [comment]
There is no method for setValueType in MetricTemplate. Currently method getValueType() return a list. MetricType has only one ValueType associated to it, it should simply has set and get method to Set ValueType.
