### ISSUE TITLE
Adding Data Instances and Data Source Instances to a CAMEL Data Model Diagram

### ISSUE THREAD

**Issue by alebagnato** [Modelio-R-D/CamelDesigner#7]
Hi there, I am using Camel Designer Beta version 0.1.05 and iI cannot manage to add Data Instance & Data Source Instance on my Data Model Diagram, No errors are shown on the UI &  some exceptions appear on the Modelio log. Please see the screenshot & the log enclosed enclosed.
Best Regards,
Alessandra
[modelio-2020-11-25-0.log](https://github.com/Modelio-R-D/CamelDesigner/files/5596901/modelio-2020-11-25-0.log)
![datainstance](https://user-images.githubusercontent.com/9965053/100233421-07261400-2f2a-11eb-95f6-ce867be126b5.jpg)

**Comment by etiennebrosse** [comment]
Data Instance and data source Instance should be created under a DataInstanceModel and not DataModel so I remove them from this view.

**Comment by alebagnato** [comment]
many thanks!
