### ISSUE TITLE
Cycle in Feature_Artifact & Feature_Connector  in CamelCore profile

### ISSUE THREAD

**Issue by Amina-Moussaoui** [Modelio-R-D/CamelDesigner#98]
"Generate" is not executed because of that

**Comment by Amina-Moussaoui** [comment]
Both cycles were deleted to generate properly on Modelio. 
What impact does it have , and how to solve it ?

**Comment by etiennebrosse** [comment]
Do you have a simple Modelio example to reproduce this cycle?

**Comment by Amina-Moussaoui** [comment]
The class inherites from itself
